---
title: "lms"
author: "Finley O'Connor"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```

#MODELING
##separate mixed effects models for all bird species
```{r herg model}
herg.vars.2 <- herg.vars %>% filter(!(is.na(cover)))
# lm.herg <-  lme4::glmer(Join_Count ~ 
#                           height + 
#                           cover + 
#                           sp_richness + 
#                           herb +
#                           vine +
#                           gram +
#                           shrub +
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = herg.vars.2)
#   plot(lm.herg)
#   summary(lm.herg)
#   qqnorm(resid(lm.herg))
  
# lm.herg1 <-  lme4::glmer(Join_Count ~ 
#                           height_class + 
#                           cover_class + 
#                           sp_richness + 
#                           herb +
#                           vine +
#                           gram +
#                           shrub +
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = herg.vars.2)
#   plot(lm.herg1)
#   summary(lm.herg1)
#   qqnorm(resid(lm.herg1)) #still not totally sure which I should be using, but the ordinal variables add a lot of extra partitioning of variance and i *think* that since the numbers increase as the observed measure (numerical) increases, it should be okay.

# tweedie.herg <- glmer(Join_Count ~ #herring gull count w/in 5m of plots
#                         Z +        #elevation, taken from ArcGIS LiDAR
#                         cover +    #total % cover
#                         sp_richness + #species richness in each plot
#                         (1|location), #island
#                     family = statmod::tweedie(var.power = 1.2, link.power = 0),
#                     data = herg.vars.2)
# plot(tweedie.herg)
# summary(tweedie.herg)
# qqnorm(resid(tweedie.herg))

# lm.hergI <-  lme4::glmer(Join_Count ~ 
#                            herb *
#                            vine *
#                            gram *
#                            shrub
#                            +
#                          #  sp_richness + (taken out bc of high correlation coeff)
#                            (1|location/gps), 
#                          family = poisson(link  = log), 
#                          data = herg.vars.2)
#   plot(lm.hergI)
#   summary(lm.hergI)
#   qqnorm(resid(lm.hergI))
#   
```
```{r herg lm}

lm.herg <- lme4::glmer(Join_Count ~
                         herb +
                         vine +
                         gram +
                         shrub +
                         (1|location/gps) +
                         (1|month),
                       family = poisson(link = log),
                       data = herg.vars.2)
  plot(lm.herg)
  summary(lm.herg)
  qqnorm(resid(lm.herg))
  isSingular(lm.herg)
drop1(lm.herg, test = "Chisq")

  # made both additive and interaction models because reasonably should be checking for interaction between the types of veg, but the model is nearly not viable due to amt of variance partitioning needed for interaction.

lm.hergC <-  lme4::glmer(Join_Count ~ 
                           Z +
                           cover +
                           sp_richness + 
                           (1|location/gps), 
                         family = poisson(link  = log), 
                         data = herg.vars.2)
  plot(lm.hergC)
  summary(lm.hergC)
  qqnorm(resid(lm.hergC))
  isSingular(lm.hergC)
drop1(lm.hergC, test = "Chisq")
  
#height and cover separated because of correlation
lm.hergH <-  lme4::glmer(Join_Count ~ 
                           Z +
                           height +
                           sp_richness + 
                           (1|location/gps), 
                         family = poisson(link  = log), 
                         data = herg.vars.2)
  plot(lm.hergH)
  summary(lm.hergH)
  qqnorm(resid(lm.hergH))
  isSingular(lm.hergH)
drop1(lm.hergH, test = "Chisq")

lm.hergHC <-  lme4::glmer(Join_Count ~ 
                           Z +
                           height +
                           cover +
                           sp_richness + 
                           (1|location/gps), 
                         family = poisson(link  = log), 
                         data = herg.vars.2)
  plot(lm.hergHC)
  summary(lm.hergHC)
  qqnorm(resid(lm.hergHC))
  isSingular(lm.hergHC)
drop1(lm.hergHC, test = "Chisq")
# #THIS ONE
#   ##*nope* too much correlation and variable inflation. use several smaller models??
#   lm.herg4 <-  lme4::glmer(Join_Count ~ 
#                           height + 
#                           cover + 
#                           sp_richness + 
#                           herb +
#                           vine +
#                           gram +
#                           shrub +
#                            Z +
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = herg.vars.2)
#   plot(lm.herg4)
#   summary(lm.herg4)
#   qqnorm(resid(lm.herg4))  

```
```{r aictab}
#herring gull
modelhergs <- list(lm.hergC, lm.hergH, lm.hergHC)
modelhergs.names <- c("lm.hergC", "lm.hergH", "lm.hergHC")
names(modelhergs) <- c("lm.hergC", "lm.hergH", "lm.hergHC")
modelhergs
aictab(modelhergs)

#great black-backed gull
modelgbbg <- list(lm.gbbgC, lm.gbbgH, lm.gbbgHC)
modelgbbg.names <- c("lm.gbbgC", "lm.gbbgH", "lm.gbbgHC")
names(modelgbbg) <- c("lm.gbbgC", "lm.gbbgH", "lm.gbbgHC")
modelgbbg
aictab(modelgbbg)
```

```{r coei model}
# coei.vars.2 <- coei.vars %>% filter(!(is.na(cover)))
# lm.coei <- lme4::glmer(Join_Count ~ 
#                          herb + 
#                          vine + 
#                          gram + 
#                          shrub + 
#                          (1|location/gps), 
#                        family = poisson (link = log), 
#                        data = coei.vars.2
#                        )
#  
#   plot(lm.coei)
#   summary(lm.coei)
#   qqnorm(resid(lm.coei))
# 
# 
# lm.coeiC <- lme4::glmer(Join_Count ~ 
#                            Z +
#                            cover +
#                            sp_richness + 
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = coei.vars.2)
#   plot(lm.coeiC)
#   summary(lm.coeiC)
#   qqnorm(resid(lm.coeiC))
#   
# lm.coeiH <- lme4::glmer(Join_Count ~ 
#                            Z +
#                            height +
#                            sp_richness + 
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = coei.vars.2)
#   plot(lm.coeiH)
#   summary(lm.coeiH)
#   qqnorm(resid(lm.coeiH))
#   
# lm.coei <- lme4::glmer(Join_Count ~ 
#                            shrub *
#                            vine *
#                            gram * 
#                            herb +
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = coei.vars.2)
#   plot(lm.coei)
#   summary(lm.coei)
#   qqnorm(resid(lm.coei))
  
```



```{r gbbg model}
gbbg.vars.2 <- gbbg.vars %>% filter(!(is.na(cover)))
#lm.gbbg <- lme4::glmer(Join_Count ~ Z + height + cover + sp_richness + herb + vine + gram + shrub + (1|location), family = poisson (link = log), data = gbbg.vars.2)
# 
# summary(lm.gbbg)
# qqnorm(resid(lm.gbbg))

lm.gbbg <- lme4::glmer(Join_Count ~
                          herb +
                          vine +
                          gram +
                          shrub +
                          (1|location), 
                        family = poisson(link = log),
                        data = gbbg.vars.2)
  plot(lm.gbbg)
  summary(lm.gbbg)
  qqnorm(resid(lm.gbbg))
  isSingular(lm.gbbg)
  drop1(lm.gbbg, test = "Chisq")
  
lm.gbbgH <- lme4::glmer(Join_Count~ 
                           Z +
                           height +
                           sp_richness + 
                           (1|location/gps), 
                         family = poisson(link  = log), 
                         data = gbbg.vars.2)
  plot(lm.gbbgH)
  summary(lm.gbbgH)
  qqnorm(resid(lm.gbbgH))
  isSingular(lm.gbbgH)
  drop1(lm.gbbgH, test = "Chisq")
  
lm.gbbgC <- lme4::glmer(Join_Count~ 
                           Z +
                           cover +
                           sp_richness + 
                           (1|location/gps), 
                         family = poisson(link  = log), 
                         data = gbbg.vars.2)
  plot(lm.gbbgC)
  summary(lm.gbbgC)
  qqnorm(resid(lm.gbbgC))
  isSingular(lm.gbbgC)
  drop1(lm.gbbgC, test = "Chisq")

lm.gbbgHC <- lme4::glmer(Join_Count~ 
                           Z +
                           height +
                           cover +
                           sp_richness + 
                           (1|location/gps), 
                         family = poisson(link  = log), 
                         data = gbbg.vars.2)
  plot(lm.gbbgHC)
  summary(lm.gbbgHC)
  qqnorm(resid(lm.gbbgHC))
  isSingular(lm.gbbgHC)
  drop1(lm.gbbgHC, test = "Chisq")
```



##models for aggregate birds
```{r aggregate gull model}
# gull.vars.2 <- gull.vars %>% filter(!(is.na(cover)))
# lm.gull <- lme4::glmer(Join_Count ~ herb + vine + gram + shrub + (1|location), family = poisson (link = log), data = gull.vars.2)
# 
# summary(lm.gull)
# qqnorm(resid(lm.gull))
# 
# lm.gull1 <- lme4::glmer(Join_Count ~ 
#                            Z +
#                            cover +
#                            height +
#                            sp_richness + 
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = gull.vars.2)
#   plot(lm.gull1)
#   summary(lm.gull1)
#   qqnorm(resid(lm.gull1))
```


```{r lm.bird}
# bird.vars.2 <- bird.vars %>% filter(!(is.na(cover)))
# lm.bird <- glmer(Join_Count ~ Z + height + cover + sp_richness + species + herb + vine + gram + shrub + (1|location), family = poisson(link = log), data = bird.vars.2)
# 
# summary(lm.bird)
# 
# lm.bird1 <- glmer(Join_Count ~ 
#                            Z +
#                            cover +
#                            height +
#                            sp_richness + 
#                            (1|location), 
#                          family = poisson(link  = log), 
#                          data = bird.vars.2)
#   plot(lm.bird1)
#   summary(lm.bird1)
#   qqnorm(resid(lm.bird1))
```




```{r glmmTMB}
# lmtmb.herg <- glmmTMB(Join_Count ~ Z + sp_richness + height + (1|location), data = herg.vars.2, family = tweedie(link = "log"), ziformula = ~., )
# summary(lmtmb.herg)
# 
# lmtmb.herg1 <- glmmTMB(Join_Count ~ herb + vine + gram + shrub + (1|location), data = herg.vars.2, family = tweedie(link = "log"), ziformula = ~., )
# summary(lmtmb.herg1)
# 
# 
# lmtmb.coei <- glmmTMB(Join_Count ~ Z + sp_richness + height + cover + shrub + gram + herb + vine + (1|location), data = coei.vars.2, family = compois(link = "log"), ziformula = ~., )
# summary(lmtmb.coei)
```

##veg models
```{r lm veg}
lm.sp_richness <- glmer(sp_richness ~ Join_Count + height + (1|location), family = poisson(link = log),data = coei.vars)
summary(lm.sp_richness)

lm.sp_richnessG <- glmer(sp_richness ~ 
                           #Join_Count + 
                           Z + 
                           height + 
                           species + 
                           (1|location), 
                         family = poisson(link = log),
                         data = bird.vars)
isSingular(lm.sp_richnessG)
vif(lm.sp_richnessG)
summary(lm.sp_richnessG)


lm.sp_rich.herg <- glmer(sp_richness ~ Join_Count + Z + height + (1|location/gps), family = poisson(link = log),data = herg.vars)
summary(lm.sp_rich.herg)
```

```{r}
vif(lm.sp_rich.herg)
```

##glm for each island
```{r shabby}
# glm.shab <- glm(Join_Count ~ 
#                   height_class + 
#                   cover_class + 
#                   sp_richness + 
#                   herb + 
#                   vine + 
#                   gram + 
#                   shrub, 
#                 family = poisson(link = log), 
#                 data = shab.vars)
# summary(glm.shab)
# qqnorm(resid(glm.shab))
# 
# glm.shab.herg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = shab.herg)
# summary(glm.shab.herg)
# 
# glm.shab.gbbg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = shab.gbbg)
# summary(glm.shab.gbbg)
# 
# glm.shab.coei <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = shab.coei)
# summary(glm.shab.coei)  ##YIKEY
```
```{r heron} 
## YIKES TO ALL OF THESE OI VEY
# glm.hrn <- glm(Join_Count ~ 
#                   Z +
#                   height_class + 
#                   cover_class + 
#                   sp_richness + 
#                   herb + 
#                   vine + 
#                   gram + 
#                   shrub, 
#                 family = poisson(link = log), 
#                 data = hrn.vars)
# summary(glm.hrn)
# qqnorm(resid(glm.hrn))
# 
# glm.hrn.herg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = hrn.herg)
# summary(glm.hrn.herg)
# 
# glm.hrn.gbbg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = hrn.gbbg)
# summary(glm.hrn.gbbg)
# 
# glm.hrn.coei <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = hrn.coei)
# summary(glm.hrn.coei)
```

```{r schoodic}
#well crap. how do I test whether my findings are true across the islands??
  #size of effect from random effect you dingus

# glm.sch <- glm(Join_Count ~ 
#                   height_class + 
#                   cover_class + 
#                   sp_richness + 
#                   herb + 
#                   vine + 
#                   gram + 
#                   shrub, 
#                 family = poisson(link = log), 
#                 data = sch.vars)
# summary(glm.sch)
# qqnorm(resid(glm.sch))
# 
# glm.sch.herg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = sch.herg)
# summary(glm.sch.herg)
# 
# glm.sch.gbbg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = sch.gbbg)
# summary(glm.sch.gbbg)
# 
# glm.sch.coei <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = sch.coei)
# summary(glm.sch.coei)
```
```{r gdi}
# glm.gdi <- glm(Join_Count ~ 
#                   species +
#                   height + 
#                   cover + 
#                   sp_richness + 
#                   herb + 
#                   vine + 
#                   gram + 
#                   shrub, 
#                 family = poisson(link = log), 
#                 data = gdi.vars)
# summary(glm.gdi)
# qqnorm(resid(glm.gdi))
# 
# glm.gdi.herg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = shab.herg)
# summary(glm.gdi.herg)
# 
# glm.gdi.gbbg <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = gdi.gbbg)
# summary(glm.gdi.gbbg)
# 
# glm.gdi.coei <- glm(Join_Count ~ 
#                        Z +
#                        height + 
#                        cover +
#                        sp_richness +
#                        herb + 
#                        vine +
#                        gram + 
#                        shrub, 
#                      family = poisson(link = log), 
#                      data = gdi.coei)
# summary(glm.gdi.coei)
```




#R2

```{r lm.herg r2}
r2_herg.mar <- partR2(lm.herg, partvars = c("herb", "vine", "gram", "shrub"), 
                  R2_type = "marginal", nboot = 15)
r2_herg.con <- partR2(lm.herg, 
                  R2_type = "conditional", nboot = 20)
#error: "Error in `[<-.data.frame`(`*tmp*`, , rcol, value = c(0L, 0L, 2L, 0L, 0L,  : replacement has 80 rows, data has 81"
#SOLUTION: Cover column has one NA entry. Filter out NA and run model again, r^2 should function.

r2_hergC <- partR2(lm.hergC, partvars = c("Z", "cover", "sp_richness"), R2_type = "marginal", nboot = 15)
r2_hergH <- partR2(lm.hergH, partvars = c("Z", "height", "sp_richness"), R2_type = "marginal", nboot = 15)
```
```{r herg r2 summary}
summary(r2_herg.mar)
summary(r2_herg.con)
summary(r2_hergC)
summary(r2_hergH)
```

```{r lm.coei r2}
# R2_coei <- partR2(lm.coei, partvars = c("Z", "height", "cover", "sp_richness", "herb", "vine", "gram", "shrub"), 
#                   R2_type = "marginal", nboot = 3)
# summary(R2_coei)
```
```{r coei.c r2}

# R2_coei.c <- partR2(lm.coei, 
#                   R2_type = "conditional", nboot = 5)
# summary(R2_coei.c)
```


```{r lm.gbbg r2}
R2_gbbg <- partR2(lm.gbbg, partvars = c("herb", "vine", "gram", "shrub"), 
                  R2_type = "marginal", nboot = 30)
summary(R2_gbbg)
```

```{r gbbg.c r2}
R2_gbbg.c <- partR2(lm.gbbg, 
                  R2_type = "conditional", nboot = 10)
summary(R2_gbbg.c)
```

```{r r2 gull}

# R2_gull <- partR2(lm.gull, partvars = c("Z", "height", "cover", "sp_richness", "herb", "vine", "gram", "shrub"), 
#                   R2_type = "marginal", nboot = 10)
# 
# R2_gull.c <- partR2(lm.gull, 
#                   R2_type = "conditional", nboot = 10)
```

```{r r2 gull summary}
# summary(R2_gull)
# summary(R2_gull.c)
```

```{r lm.bird r2}
# R2_bird <- partR2(lm.bird, partvars = c( "species", "Z", "height", "cover", "sp_richness", "herb", "vine", "gram", "shrub"),
#                   data = bird.vars.2, R2_type = "marginal", nboot = 5)
# R2_bird.c <- partR2(lm.bird, 
#                   R2_type = "conditional", nboot = 10)
```

```{r}
# summary(R2_bird)
```
```{r veg r2}
R2_veg <- partR2(lm.sp_richness1, partvars = c("Z", "height", "Join_Count"), 
                  R2_type = "marginal", nboot = 10)

R2_veg.c <- partR2(lm.sp_richness1, 
                  R2_type = "conditional", nboot = 10)
```

```{r}
summary(R2_veg)
summary(R2_veg.c)
```
#CORRELATION
##variance inflation factors
```{r herg cor}
vif(lm.herg)
vif(lm.hergC)
vif(lm.hergH)
vif(lm.hergHC)

cor.test(x = herg.vars.2$cover, 
         y = herg.vars.2$height, 
         method = 'spearman')
cor.test(x = herg.vars.2$cover, 
         y = herg.vars.2$sp_richness, 
         method = 'spearman')
cor.test(x = herg.vars.2$cover, 
         y = herg.vars.2$Z, 
         method = 'spearman')
cor.test(x = herg.vars.2$height, 
         y = herg.vars.2$sp_richness, 
         method = 'spearman')
cor.test(x = herg.vars.2$Z,
         y = herg.vars.2$sp_richness, 
         method = 'spearman')
```
```{r gbbg cor}
vif(lm.gbbgC)
vif(lm.gbbgH)
vif(lm.gbbg)
```

```{r coei cor}
vif(lm.coeiC)
vif(lm.coeiH)
vif(lm.coei)
```

```{r}
cor.test(x = herg.vars.2$vine, y = herg.vars.2$herb, method = 'spearman')
cor.test(x = herg.vars.2$herb, y = herg.vars.2$shrub, method = 'spearman')
```

```{r veg}
vif(lm.sp_richness)
vif(lm.sp_richness1)

cor.test(x = bird.vars.2$sp_richness, y = bird.vars.2$Z, method = 'spearman')
```

