---
title: "preliminary"
author: "Finley O'Connor"
date: "2024-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#base_dir = "C:/Users/ronan/Desktop/STATS/Senior-Project/"
```



```{r load-packages, message = FALSE}
library(tidyverse)
library(magrittr)
library(broom)
library(leaflet) ## For leaflet interactive maps
library(sf) ## For spatial data
library(RColorBrewer) ## For colour palettes
library(htmltools) ## For html
library(leafsync) ## For placing plots side by side
library(stringr) ## For character string manipulation
library(kableExtra) ## Table  output (in slides)
library(visdat)
library(naniar)
library(readxl) ##working with xcel sheets
library(ggridges)
library(dataCompareR)
library(stringr)
```

### READ IN DATA
```{r read-in-vegetation-file, echo = FALSE}
island_veg <- read_csv("data/island_veg.csv")
veg_attributes <- read_csv("data/plotpointsattributes.csv")
gdi_attributes <- read_csv("data/gdipointsattributes.csv")
smpl_attributes <- read_csv("data/sampled.csv")
```
```{r fix-gdi-attributes}
gdi_attributes <- gdi_attributes %>%
  mutate(name = paste0('gdi',gdi_attributes$OID_))
```
-
```{r join-gdi}
veg_attributes <- full_join(veg_attributes, gdi_attributes)
```
-
```{r read-in-bird-files, echo = FALSE}
gdi_bird <- st_read("data/gull data/gdi_nests/gdi_nests_Merge.shp")
heron_bird <- st_read("data/gull data/heron_nests/herg_nests_heron.shp")
schoodic_bird <- st_read("data/gull data/schoodic_nests/all_nests.shp")
shabby_bird <- st_read("data/gull data/shabby_nests/gull_eider_nests.shp")
```

###TIDYING

#Tidy bird data
```{r create-location-colmn-birds}
gdi_bird$location <- c("gdi")
heron_bird$location <- c("heron")
shabby_bird$location <- c("shabby")
schoodic_bird$location <- c("schoodic")
```
-
```{r recode-shabby-column-names}
  colnames(shabby_bird)[which(names(shabby_bird) == "Point_ge_4")] <- "GPS_Date"
  colnames(shabby_bird)[which(names(shabby_bird) == "shabby_i_2")] <- "species"
  colnames(shabby_bird)[which(names(shabby_bird) == "Point_gene")] <- "Point_ID"
```
-
```{r recode-schoodic-column-names}
  colnames(schoodic_bird)[which(names(schoodic_bird) == "all_nest_3")] <- "GPS_Date"
  colnames(schoodic_bird)[which(names(schoodic_bird) == "schoodic_2")] <- "species"
  colnames(schoodic_bird)[which(names(schoodic_bird) == "schoodic_c")] <- "Point_ID"
```
-
```{r select-relevant-columns-in-bird-data}
gdi_bird_all <- gdi_bird %>%
  select(Point_ID, GPS_Date, species, location, geometry)
 
heron_bird_all <- heron_bird %>%
  mutate(species = "herring gull") %>% #create species column for heron
  select(Point_ID, GPS_Date, species, location, geometry)
  
shabby_bird_all <- shabby_bird %>%
  select(Point_ID, GPS_Date, species, location, geometry)

schoodic_bird_all <- schoodic_bird %>%
  select(Point_ID, GPS_Date, species, location, geometry)
```
-
```{r combine-bird-datasets-for-all-islands}
island_bird <- rbind(gdi_bird_all, heron_bird_all, shabby_bird_all, schoodic_bird_all)
```


```{r change_coordinate_system_for_bird}
#update bird data to the coordinate system used in leaflet
island_bird <- st_transform(island_bird, "+init=epsg:4326")
```

```{r mutate_column_for_long_and_lat}
island_bird$geometry
```


#Tidy vegetation data
```{r join veg & coordinates}
island_veg <- island_veg %>% 
  mutate(name = gps)

island_veg_all <- island_veg %>% 
                  left_join(veg_attributes, island_veg, by = "name")
```
-
```{r standardize-island-naming}
island_veg_all <- island_veg_all %>%
  mutate(location = case_when(
    location == "Schoodic" ~ "schoodic",
    location == "GDI" ~ "gdi",
    TRUE ~ location
  ))
```
-
```{r recode-veg-height-class-names}
 island_veg_all <- island_veg_all %>%
mutate(height_class = case_when(TRUE ~ as.factor(height))) %>% #making height class a factor variable in order to use it in a bar chart
  mutate(height_class_range = case_when(
    height_class == "1" ~ "0-0.15",
    height_class == "2" ~ "0.15-0.30",
    height_class == "3" ~ "0.30-1",
    height_class == "4" ~ "1-1.5",
    height_class == "5" ~ "1.5+"
  ))
```
-
```{r recode-veg-cover-names}
island_veg_all <- island_veg_all %>%
  mutate(percent_cover_range = case_when(
    cover == "1" ~ "0-0.01",
    cover == "5" ~ "0.02-0.05",
    cover == "25" ~ "0.06-0.25",
    cover == "50" ~ "0.26-0.50",
    cover == "75" ~ "0.51-0.75",
    cover == "100" ~ "0.76-1.00"
  ))
```
-
```{r standardize spp (veg)}
island_veg_all <- island_veg_all %>%
  mutate(spp = case_when(
    spp == "achillea millefolium" ~ "Achillea millefolium",
    spp == "agrostis scabra" ~ "Agrostis scabra",
    spp == "agrostis stolonifera" ~ "Agrostis stolonifera",
    spp == "arctium sp" ~ "Arctium sp.",
    spp == "calystegia sepium" ~ "Calystegia sepium",
    spp == "carex nigra" ~ "Carex nigra",
    spp == "cerastium arvense" ~ "Cerastium arvense",
    spp == "cerastium fontana" ~ "Cerastium fontanum",
    spp == "cerastium fontanum" ~ "Cerastium fontanum",
    spp == "cirsium arvense" ~ "Cirsium arvense",
    spp == "cirsium vulgare" ~ "Cirsium vulgare",
    spp == "cornus canadensis" ~ "Cornus canadensis",
    spp == "cuscuta gronovii" ~ "Cuscuta gronovii",
    spp == "doellingeria umbellata" ~ "Doellingeria umbellata",
    spp == "festuca rubra" ~ "Festuca rubra",
    spp == "fragaria virginiana" ~ "Fragaria virginiana",
    spp == "hieracium caespitosum" ~ "Hieracium caespitosum",
    spp == "impatiens capensis" ~ "Impatiens capensis",
    spp == "iris versicolor" ~ "Iris versicolor",
    spp == "lathyrus japonicus" ~ "Lathyrus japonicus",
    spp == "lathyrus palustris" ~ "Lathyrus palustris",
    spp == "luzula multiflora" ~ "Luzula multiflora",
    spp == "maianthemum canadense" ~ "Maianthemum canadense",
    spp == "matricaria discoidea" ~ "Matricaria discoidea",
    spp == "myrica gale" ~ "Myrica gale",
    spp == "osmundastrum cinnamomeum" ~ "Osmundastrum cinnamomeum",
    spp == "plantago major" ~ "Plantago major",
    spp == "poa pratensis" ~ "Poa pratensis",
    spp == "Poa spp (tufting)" ~ "Poa sp.",
    spp == "potentilla anserina" ~ "Potentilla anserina",
    spp == "potentilla norvegica" ~ "Potentilla norvegica",
    spp == "potentilla simplex" ~ "Potentilla simplex",
    spp == "ranunculus acris" ~ "Ranunculus acris",
    spp == "rubus hispidus" ~ "Rubus hispidus",
    spp == "rubus idaeus" ~ "Rubus idaeus",
    spp == "rumex acetosella" ~ "Rumex acetosella",
    spp == "rumex longifolius" ~ "Rumex longifolius",
    spp == "rumex sp." ~ "Rumex sp.",
    spp == "scutellaria galericulata" ~ "Scutellaria galericulata",
    spp == "solanum dulcamara" ~ "Solanum dulcamara",
    spp == "solidago rugosa" ~ "Solidago rugosa",
    spp == "solidago sempervirens" ~ "Solidago sempervirens",
    spp == "spiraea alba" ~ "Spiraea alba",
    spp == "stellaria media" ~ "Stellaria media",
    spp == "Strawberry" ~ "Fragaria virginiana",
    spp == "symphotrichum novae-angliae" ~ "Symphotrichum novae-angliae",
    spp == "taraxacum officinale" ~ "Taraxacum officinale",
    spp == "taraxacum officionale" ~ "Taraxacum officinale",
    spp == "trifolium repens" ~ "Trifolium repens",
    spp == "urtica dioica" ~ "Urtica dioica",
    spp == "vaccinium angustifolium" ~ "Vaccinium angustifolium",
    spp == "valeriana officionalis" ~ "Valeriana officinalis",
    spp == "Valeriana officionalis" ~ "Valeriana officinalis",
    spp == "valeriana officinalis" ~ "Valeriana officinalis",
    spp == "veronica arvensis" ~ "Veronica arvensis",
    TRUE ~ spp
  ))
print(island_veg_all)
```
-
```{r insert IDs (veg)}
island_veg_all <- island_veg_all %>%
  mutate(spp = case_when(
    spp == "Min lat" ~ "Moehringia lateriflora",
    spp == "Calamagrostis #8" ~ "Poa pratensis",
    spp == "grass #54" ~ "Poa pratensis",
    spp == "Poa pratensis (#16)" ~ "Poa pratensis",
    spp == "Poa pratensis #16)" ~ "Poa pratensis",
    spp == "Poa spp #19" ~ "Alopecurus pratensis",
    spp == "elymus #33" ~ "Elymus trachycaulus",
    spp == "grass #74" ~ "Agrostis stolonifera",
    spp == "Poa #3" ~ "Poa trivialis",
    spp == "#53" ~ "Capsella bursa-pastoris",
    spp == "Poaceae #84" ~ "Elymus repens",
    spp == "Sedge #82" ~ "Carex silicea",
    spp == "Dock sp #45" ~ "Rumex britannica",
    spp == "dock sp #51" ~ "Rumex crispa",
    spp == "Poaceae #22" ~ "Anthoxanthum odoratum",
    spp == "Vetch #99" ~ "Lathyrus palustris",
    spp == "#36" ~ "Epilobium ciliatum",
    spp == "lamiaceae #70" ~ "Galeopsis bifida",
    spp == "lamiaceae #90" ~ "Lycopus uniflorus",
    spp == "#13" ~ "Capsella bursa-pastoris", 
    spp == "#5" ~ "Solidago puberula", 
    spp == "#7" ~ "Ribes glandulosum",
    spp == "Atriplex #35" ~ "Atriplex subspicata", 
    spp == "Caryophalles (#77)" ~ "Cerastium arvense",
    spp == "Cleavers (#37)" ~ "Galium sylvaticum", 
    spp == "Lamiales (#39)" ~ "Scutellaria galericulata", 
    spp == "Poa spp #73" ~ "Poa pratensis", 
    spp == "potentilla/geum #83" ~ "Potentilla norvegica", 
    spp == "Rosaceae #95" ~ "Fragaria virginiana", 
    spp == "Rubus shrub spp. (#32)" ~ "Rubus idaeus", 
    spp == "Solidago #2" ~ "Solidago sempervirens", 
    spp == "Solidago #64" ~ "Solidago puberula", 
    spp == "Solidago (#100)" ~ "Solidago sempervirens", 
    spp == "Solidago (#64)" ~ "Solidago puberula", 
    spp == "Thistle (#75)" ~ "Cirsium vulgare", 
    spp == "Veronica #1" ~ "Veronica arvensis",
    spp == "yell. Brassicaceae #58" ~ "Raphanus raphanistrum", 
    spp == "Lamiaceae #30" ~ "Angelica lucida",
    TRUE ~ spp
  ))
```
-
```{r create-veg-types}
island_veg_all$type <- "NA"
```
-
```{r assign-veg-types}
island_veg_all <- island_veg_all %>%
  # select(location:percent_cover_range) %>%
   mutate(type = case_when(
    spp == "Achillea millefolium" ~ "herb",
    spp == "Agrostis scabra" ~ "gram",
    spp == "Agrostis stolonifera" ~ "gram",
    spp == "Arctium sp." ~ "herb",
    spp == "Calystegia sepium" ~ "vine",
    spp == "Carex nigra" ~ "gram",
    spp == "Cerastium arvense" ~ "herb",
    spp == "Cerastium fontanum" ~ "herb",
    spp == "Cerastium fontanum" ~ "herb",
    spp == "Cirsium arvense" ~ "herb",
    spp == "Cirsium vulgare" ~ "herb",
    spp == "Cornus canadensis" ~ "herb",
    spp == "Cuscuta gronovii" ~ "vine",
    spp == "Doellingeria umbellata" ~ "herb",
    spp == "Festuca rubra" ~ "gram",
    spp == "Fragaria virginiana" ~ "herb",
    spp == "Hieracium caespitosum" ~ "herb",
    spp == "Impatiens capensis" ~ "herb",
    spp == "Iris versicolor" ~ "herb",
    spp == "Lathyrus japonicus" ~ "vine",
    spp == "Lathyrus palustris" ~ "vine",
    spp == "Luzula multiflora" ~ "gram",
    spp == "Maianthemum canadense" ~ "herb",
    spp == "Matricaria discoidea" ~ "herb",
    spp == "Myrica gale" ~ "shrub",
    spp == "Osmundastrum cinnamomeum" ~ "herb",
    spp == "Plantago major" ~ "herb",
    spp == "Poa pratensis" ~ "gram",
    spp == "Poa sp." ~ "gram",
    spp == "Potentilla anserina" ~ "herb",
    spp == "Potentilla norvegica" ~ "herb",
    spp == "Potentilla simplex" ~ "herb",
    spp == "Ranunculus acris" ~ "herb",
    spp == "Rubus hispidus" ~ "vine",
    spp == "Rubus idaeus" ~ "shrub",
    spp == "Rumex acetosella" ~ "herb",
    spp == "Rumex longifolius" ~ "herb",
    spp == "Rumex sp." ~ "herb",
    spp == "Rubus shrub spp. (#32)" ~ "shrub",
    spp == "Scutellaria galericulata" ~ "herb",
    spp == "Solanum dulcamara" ~ "vine",
    spp == "Solidago rugosa" ~ "herb",
    spp == "Solidago sempervirens" ~ "herb",
    spp == "Spiraea alba" ~ "shrub",
    spp == "Stellaria media" ~ "herb",
    spp == "Symphotrichum novae-angliae" ~ "herb",
    spp == "Taraxacum officinale" ~ "herb",
    spp == "Trifolium repens" ~ "herb",
    spp == "Urtica dioica" ~ "herb",
    spp == "Vaccinium angustifolium" ~ "shrub",
    spp == "Valeriana officinalis" ~ "herb",
    spp == "Veronica arvensis" ~ "herb",
    spp == "Epilobium ciliatum" ~ "herb",
    TRUE ~ type
  ))
```
##visualize the dataset
```{r find-unique-species-veg}
unique <- unique(island_veg_all$spp)
sort(unique)
```

```{r writing-CSVs}
write_csv(island_veg_all, "island_veg_all.csv")

```


