---
title: "tidy"
author: "Finley O'Connor"
date: "2024-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message = FALSE}
library(tidyverse)
library(dplyr)
library(magrittr)
library(broom)
library(leaflet) ## For leaflet interactive maps
library(sf) ## For spatial data
library(RColorBrewer) ## For colour palettes
library(htmltools) ## For html
library(leafsync) ## For placing plots side by side
library(stringr) ## For character string manipulation
library(kableExtra) ## Table  output (in slides)
library(visdat)
library(naniar)
library(readxl) ##working with xcel sheets
library(ggridges)
library(dataCompareR)

library(lme4)
#library(afex) #pulls p-values from GLM
library(partR2) #derive r2 values from GLM
library(TMB)
library(glmmTMB)
library(car)
library(statmod)
```

```{r read-in-vegetation-file, echo = FALSE}
island_veg <- read_csv("gitdata/island_veg_amended.csv")
veg_attributes <- read_excel("gitdata/plotpointattributes_TableToExcel.xlsx")
gdi_attributes <- read_excel("gitdata/gdipointsattributes_TableToExcel.xlsx")

```

```{r fix-gdi-attributes}
gdi_attributes <- gdi_attributes %>%
  mutate(name = paste0('gdi',gdi_attributes$OBJECTID))
```

```{r join-gdi}
veg_attributes <- bind_rows(veg_attributes, gdi_attributes)
```

```{r join veg & coordinates}
island_veg <- island_veg %>% 
  mutate(name = gps)

island_veg_all <- island_veg %>% 
                  left_join(veg_attributes, island_veg, by = "name")
```
-
```{r standardize-island-naming}
island_veg_all <- island_veg_all %>%
  mutate(location = case_when(
    location == "Schoodic" ~ "schoodic",
    location == "GDI" ~ "gdi",
    TRUE ~ location
  ))
```

```{r recode-veg-height}
 island_veg_all <- island_veg_all %>%
mutate(height_class = case_when(TRUE ~ as.ordered(height))) %>% #making height class a factor variable
mutate(cover_class = case_when(TRUE ~ as.ordered(cover))) #making cover class a factor variable
```

```{r create-veg-types}
island_veg_all$type <- "NA"
island_veg_all$arm<- "NA"
```

```{r}
spp_list <- unique(island_veg_all$spp)
spp_list <- as.data.frame(spp_list)
  colnames(spp_list) <- "spp"
```

#mutate island_veg_all
```{r add type, arm, genus}
island_veg_all <- island_veg_all %>%
    mutate(type = case_when(
      spp == "Valeriana officionalis" ~ "herb",
      spp == "Taraxacum officionale" ~ "herb",
      spp == "Urtica dioica" ~ "herb",
      spp == "Fragaria virginiana" ~ "herb",
      spp == "Cerastium arvense" ~ "herb",
      spp == "Veronica arvensis"~ "herb",
      spp == "Solidago puberula"~ "herb",
      spp == "Solanum dulcamara"~ "herb",
      spp == "Cirsium vulgare"~ "herb",
      spp == "Calystegia sepium"~ "vine",
      spp == "Poa trivialis"~ "gram",
      spp == "Trifolium repens"~ "herb",
      spp == "Ranunculus acris"~ "herb",
      spp == "Poa pratensis"~ "gram",
      spp == "Lathyrus palustris"~ "vine",
      spp == "Rubus idaeus"~ "shrub",
      spp == "Alepecurus pratensis"~ "gram",
      spp == "Solidago sempervirens"~ "herb",
      spp == "Galium sylvaticum"~ "herb",
      spp == "Plantago major"~ "herb",
      spp == "Poa spp (tufting)"~ "gram",
      spp == "Lathyrus japonicus"~ "vine",
      spp == "Iris versicolor" ~ "herb",
      spp == "Scutellaria galericulata"~ "herb",
      spp == "Potentilla anserina"~ "herb",
      spp == "Elymus repens"~ "gram",
      spp == "Achillea millefolium"~ "herb",
      spp == "Maianthemum canadense"~ "herb",
      spp == "Carex silicea"~ "gram",
      spp == "Rumex pallidus"~ "herb",
      spp == "Arctium sp."~ "herb",
      spp == "Cirsium sp."~ "herb",
      spp == "young yarrow? #56"~ "herb",
      spp == "Mentha canadensis"~ "herb",
      spp == "Epilobium ciliatum"~ "herb",
      spp == "Atriplex subspicata"~ "herb",
      spp == "Capsella bursa-pastoris"~ "herb",
      spp == "Matricaria discoidea"~ "herb",
      spp == "Festuca rubra"~ "gram",
      spp == "Doellingeria umbellata"~ "herb",
      spp == "Rubus hispidus"~ "herb", ##coded as herb because of sub-shrubbiness
      spp == "Agrostis stolonifera"~ "gram",
      spp == "Hieracium caespitosum"~ "herb",
      spp == "Rumex acetosella"~ "herb",
      spp == "Rumex britannica"~ "herb",
      spp == "Solidago rugosa"~ "herb",
      spp == "Cuscuta gronovii"~ "vine",
      spp == "Impatiens capensis"~ "herb",
      spp == "Angelica lucida"~ "herb",
      spp == "Cornus canadensis" ~ "herb",
      spp == "Moehringia lateriflora" ~ "herb",
      spp == "Carex nigra" ~ "gram",
      spp == "Vaccinium angustifolium" ~ "herb", ##coded as herb because of sub-shrubbiness
      spp == "Luzula multiflora" ~ "gram",
      spp == "Anthoxanthum odoratum" ~ "gram",
      spp == "Stellaria media" ~ "herb",
      spp == "Myrica gale" ~ "shrub",
      spp == "Rumex crispus" ~ "herb",
      spp == "Plantago maritima" ~ "herb",
      spp == "Cirsium arvense" ~ "herb",
      spp == "Galeopsis bifida" ~ "herb",
      spp == "Elymus trachycaulus" ~ "gram",
      spp == "Ribes glandulosum" ~ "shrub",
      spp == "Osmundastrum cinnamomeum" ~ "herb",
      spp == "Rumex sp." ~ "herb",
      spp == "Raphanus raphanistrum" ~ "herb",
      spp == "Spiraea alba" ~ "shrub",
      spp == "Symphyotrichum novae-angliae" ~ "herb",
      spp == "Lycopus uniflorus" ~ "herb",
      spp == "Agrostis scabra" ~ "gram",
      spp == "Cerastium fontanum" ~ "herb",
      spp == "Potentilla simplex" ~ "herb",
      spp == "Potentilla norvegica" ~ "herb",
      spp == "Rumex longifolius" ~ "herb",
      TRUE ~ type
      ))

island_veg_all <- island_veg_all %>%
    mutate(arm = case_when(
      spp == "Valeriana officionalis" ~ "0",
      spp == "Taraxacum officionale" ~ "0",
      spp == "Urtica dioica" ~ "1",
      spp == "Fragaria virginiana" ~ "0",
      spp == "Cerastium arvense" ~ "0",
      spp == "Veronica arvensis"~ "0",
      spp == "Solidago puberula"~ "0",
      spp == "Solanum dulcamara"~ "0",
      spp == "Cirsium vulgare"~ "1",
      spp == "Calystegia sepium"~ "0",
      spp == "Poa trivialis"~ "0",
      spp == "Trifolium repens"~ "0",
      spp == "Ranunculus acris"~ "0",
      spp == "Poa pratensis"~ "0",
      spp == "Lathyrus palustris"~ "0",
      spp == "Rubus idaeus"~ "1",
      spp == "Alepecurus pratensis"~ "0",
      spp == "Solidago sempervirens"~ "0",
      spp == "Galium sylvaticum"~ "0",
      spp == "Plantago major"~ "0",
      spp == "Poa spp (tufting)"~ "0",
      spp == "Lathyrus japonicus"~ "0",
      spp == "Iris versicolor" ~ "0",
      spp == "Scutellaria galericulata"~ "0",
      spp == "Potentilla anserina"~ "1",
      spp == "Elymus repens"~ "0",
      spp == "Achillea millefolium"~ "0",
      spp == "Maianthemum canadense"~ "0",
      spp == "Carex silicea"~ "0",
      spp == "Rumex pallidus"~ "0",
      spp == "Arctium sp."~ "0",
      spp == "Cirsium sp."~ "1",
      spp == "young yarrow? #56"~ "0",
      spp == "Mentha canadensis"~ "0",
      spp == "Epilobium ciliatum"~ "0",
      spp == "Atriplex subspicata"~ "0",
      spp == "Capsella bursa-pastoris"~ "0",
      spp == "Matricaria discoidea"~ "0",
      spp == "Festuca rubra"~ "0",
      spp == "Doellingeria umbellata"~ "0",
      spp == "Rubus hispidus"~ "1",
      spp == "Agrostis stolonifera"~ "0",
      spp == "Hieracium caespitosum"~ "0",
      spp == "Rumex acetosella"~ "0",
      spp == "Rumex britannica"~ "0",
      spp == "Solidago rugosa"~ "0",
      spp == "Cuscuta gronovii"~ "0",
      spp == "Impatiens capensis"~ "0",
      spp == "Angelica lucida"~ "0",
      spp == "Cornus canadensis" ~ "0",
      spp == "Moehringia lateriflora" ~ "0",
      spp == "Carex nigra" ~ "0",
      spp == "Vaccinium angustifolium" ~ "0",
      spp == "Luzula multiflora" ~ "0",
      spp == "Anthoxanthum odoratum" ~ "0",
      spp == "Stellaria media" ~ "0",
      spp == "Myrica gale" ~ "0",
      spp == "Rumex crispus" ~ "0",
      spp == "Plantago maritima" ~ "0",
      spp == "Cirsium arvense" ~ "1",
      spp == "Galeopsis bifida" ~ "0",
      spp == "Elymus trachycaulus" ~ "0",
      spp == "Ribes glandulosum" ~ "0",
      spp == "Osmundastrum cinnamomeum" ~ "0",
      spp == "Rumex sp." ~ "0",
      spp == "Raphanus raphanistrum" ~ "0",
      spp == "Spiraea alba" ~ "0",
      spp == "Symphyotrichum novae-angliae" ~ "0",
      spp == "Lycopus uniflorus" ~ "0",
      spp == "Agrostis scabra" ~ "0",
      spp == "Cerastium fontanum" ~ "0",
      spp == "Potentilla simplex" ~ "0",
      spp == "Potentilla norvegica" ~ "0",
      spp == "Rumex longifolius" ~ "0",
      TRUE ~ "0"
      )) %>%
  mutate(arm = as.numeric(arm))


island_veg_all <- island_veg_all %>%
    mutate(genus = case_when(
      spp == "Valeriana officionalis" ~ "Valeriana",
      spp == "Taraxacum officionale" ~ "Taraxacum",
      spp == "Urtica dioica" ~ "Urtica",
      spp == "Fragaria virginiana" ~ "Fragaria",
      spp == "Cerastium arvense" ~ "Cerastium",
      spp == "Veronica arvensis"~ "Veronica",
      spp == "Solidago puberula"~ "Solidago",
      spp == "Solanum dulcamara"~ "Solanum",
      spp == "Cirsium vulgare"~ "Cirsium",
      spp == "Calystegia sepium"~ "Calystegia",
      spp == "Poa trivialis"~ "Poa",
      spp == "Trifolium repens"~ "Trifolium",
      spp == "Ranunculus acris"~ "Ranunculus",
      spp == "Poa pratensis"~ "Poa",
      spp == "Lathyrus palustris"~ "Lathyrus",
      spp == "Rubus idaeus"~ "Rubus idaeus",
      spp == "Alepecurus pratensis"~ "Alepecurus",
      spp == "Solidago sempervirens"~ "Solidago",
      spp == "Galium sylvaticum"~ "Galium",
      spp == "Plantago major"~ "Plantago",
      spp == "Poa spp (tufting)"~ "Poa",
      spp == "Lathyrus japonicus"~ "Lathyrus",
      spp == "Iris versicolor" ~ "Iris",
      spp == "Scutellaria galericulata"~ "Scutellaria",
      spp == "Potentilla anserina"~ "Potentilla",
      spp == "Elymus repens"~ "Elymus",
      spp == "Achillea millefolium"~ "Achillea",
      spp == "Maianthemum canadense"~ "Maianthemum",
      spp == "Carex silicea"~ "Carex",
      spp == "Rumex pallidus"~ "Rumex",
      spp == "Arctium sp."~ "Arctium",
      spp == "Cirsium sp."~ "Cirsium",
      spp == "young yarrow? #56"~ "Achillea",
      spp == "Mentha canadensis"~ "Mentha",
      spp == "Epilobium ciliatum"~ "Epilobium",
      spp == "Atriplex subspicata"~ "Atriplex",
      spp == "Capsella bursa-pastoris"~ "Capsella",
      spp == "Matricaria discoidea"~ "Matricaria",
      spp == "Festuca rubra"~ "Festuca",
      spp == "Doellingeria umbellata"~ "Doellingeria",
      spp == "Rubus hispidus"~ "Rubus hispidus",
      spp == "Agrostis stolonifera"~ "Agrostis",
      spp == "Hieracium caespitosum"~ "Hieracium",
      spp == "Rumex acetosella"~ "Rumex",
      spp == "Rumex britannica"~ "Rumex",
      spp == "Solidago rugosa"~ "Solidago",
      spp == "Cuscuta gronovii"~ "Cuscuta",
      spp == "Impatiens capensis"~ "Impatiens",
      spp == "Angelica lucida"~ "Angelica",
      spp == "Cornus canadensis" ~ "Cornus",
      spp == "Moehringia lateriflora" ~ "Moehringia",
      spp == "Carex nigra" ~ "Carex",
      spp == "Vaccinium angustifolium" ~ "Vaccinium",
      spp == "Luzula multiflora" ~ "Luzula",
      spp == "Anthoxanthum odoratum" ~ "Anthoxanthum",
      spp == "Stellaria media" ~ "Stellaria",
      spp == "Myrica gale" ~ "Myrica",
      spp == "Rumex crispus" ~ "Rumex",
      spp == "Plantago maritima" ~ "Plantago",
      spp == "Cirsium arvense" ~ "Cirsium",
      spp == "Galeopsis bifida" ~ "Galeopsis",
      spp == "Elymus trachycaulus" ~ "Elymus",
      spp == "Ribes glandulosum" ~ "Ribes",
      spp == "Osmundastrum cinnamomeum" ~ "Osmundastrum",
      spp == "Rumex sp." ~ "Rumex",
      spp == "Raphanus raphanistrum" ~ "Raphanus",
      spp == "Spiraea alba" ~ "Spiraea",
      spp == "Symphyotrichum novae-angliae" ~ "Symphotryichum",
      spp == "Lycopus uniflorus" ~ "Lycopus",
      spp == "Agrostis scabra" ~ "Agrostis",
      spp == "Cerastium fontanum" ~ "Cerastium",
      spp == "Potentilla simplex" ~ "Potentilla",
      spp == "Potentilla norvegica" ~ "Potentilla",
      spp == "Rumex longifolius" ~ "Rumex",
      TRUE ~ spp
      ))
```

```{r add month}
island_veg_all <- island_veg_all %>%
    mutate(month = case_when(
      date == "5/27/2023" ~ "5",
      date == "5/31/2023" ~ "5",
      date == "7/12/2023" ~ "7",
      date == "8/12/2023" ~ "8"
    ))
```



#spp_list
```{r}
spp_list <- island_veg_all %>% select(spp, type, arm)
spp_list <- distinct(spp_list)

```

```{r}
spp_list %>% 
  group_by(type)
  
write.table(spp_list, file = "spp_list.csv")
```

#species richness
```{r}
rich.notna <- island_veg_all %>%
  filter(!(is.na(spp))) %>%
  group_by(gps) %>%
  count(gps) %>% 
  rename(sp_richness = n) #sp richness count for non-na rows

rich.na <- island_veg_all %>%
  filter(is.na(spp)) %>%
  mutate(sp_richness = 0) #sp richness count for NAs

filtered <- island_veg_all %>%
  select(location,gps,date, month, cover, cover_class, height, height_class, POINT_X, POINT_Y, Z, arm)

model.vars <- rbind(rich.notna,rich.na) %>%
  select(1:2) %>%
  left_join(filtered, by = "gps") %>%
  distinct(gps, .keep_all = TRUE)
```

```{r make structure + model.vars}
structure <- island_veg_all %>%
  select(gps, type) %>%
  mutate(presence = "1") %>%
  pivot_wider(id_cols = gps, names_from = type, values_from = presence) %>%
  mutate(herb = case_when(herb == "NULL" ~ "0",
                          TRUE ~ "1")) %>%
  mutate(vine = case_when(vine == "NULL" ~ "0",
                          TRUE ~ "1")) %>%
  mutate(shrub = case_when(shrub == "NULL" ~ "0",
                          TRUE ~ "1")) %>%
  mutate(gram = case_when(gram == "NULL" ~ "0",
                          TRUE ~ "1")) %>%
  select(gps, herb, vine, gram, shrub)

structure <- structure %>% 
  mutate(herb = as.factor(herb)) %>%
  mutate(vine = as.factor(vine)) %>%
  mutate(shrub = as.factor(shrub)) %>%
  mutate(gram = as.factor(gram))

# structure <- test %>%
#   select(gps, herb, vine, gram, shrub)

 model.vars <- left_join(model.vars, structure, by = "gps") 
 

``` 

#bird data
```{r read in non-GDI bird counts}
# herg_count <- read_excel("gitdata/herg_buff_count_TableToExcel.xlsx")
# coei_count <- read_excel("gitdata/coei_buff_count_TableToExcel.xlsx")
# gbbg_count <- read_excel("gitdata/gbbg_buff_count_TableToExcel.xlsx")

herg_count <- read_excel("gitdata/plot_buff_5m_herg_TableToExcel.xlsx")
coei_count <- read_excel("gitdata/plot_buff_5m_coei_TableToExcel.xlsx")
gbbg_count <- read_excel("gitdata/plot_buff_5m_gbbg_TableToExcel.xlsx")
```

```{r read in GDI bird counts}
# gdi_herg_count <- read_excel("gitdata/gdi_herg_buff_count.xls")
# gdi_coei_count <- read_excel("gitdata/gdi_coei_buff_count.xls")
# gdi_gbbg_count <- read_excel("gitdata/gdi_gbbg_buff_count_TableToExcel.xlsx")

gdi_herg_count <- read_excel("gitdata/gdi_buff_5m_herg_TableToExcel.xlsx")
gdi_coei_count <- read_excel("gitdata/gdi_buff_5m_coei_TableToExcel.xlsx")
gdi_gbbg_count <- read_excel("gitdata/gdi_buff_5m_gbbg_TableToExcel.xlsx")
```

```{r fix GDI bird counts}
gdi_herg_count <- gdi_herg_count %>%
  mutate(gps = paste0('gdi',gdi_herg_count$OBJECTID))

gdi_coei_count <- gdi_coei_count %>%
  mutate(gps = paste0('gdi',gdi_coei_count$OBJECTID))

gdi_gbbg_count <- gdi_gbbg_count %>%
  mutate(gps = paste0('gdi',gdi_gbbg_count$OBJECTID))
```

```{r tidy and join bird dataframes (make _buffs & .vars) }

#combine GDI and all other islands
herg_buff <- bind_rows(gdi_herg_count, herg_count)
coei_buff <- bind_rows(gdi_coei_count, coei_count)
gbbg_buff <- bind_rows(gdi_gbbg_count, gbbg_count)

#trim down to sampled points
herg_buff <- herg_buff %>%
  select(Join_Count, gps, species) %>%
  subset(gps %in% model.vars$gps)
coei_buff <- coei_buff %>%
  select(Join_Count, gps, species) %>%
  subset(gps %in% model.vars$gps)
gbbg_buff <- gbbg_buff %>%
  select(Join_Count, gps, species) %>%
  subset(gps %in% model.vars$gps)

#join bird counts with model.var
herg.vars <- model.vars %>%
  left_join(herg_buff, by = "gps")
coei.vars <- model.vars %>%
  left_join(coei_buff, by = "gps")
gbbg.vars <- model.vars %>%
  left_join(gbbg_buff, by = "gps")

#combine gull data
gull.vars <- bind_rows(herg.vars, gbbg.vars)

#all species model.var dataframe
bird.vars <- bind_rows(herg.vars, coei.vars, gbbg.vars)

#by island
shab.vars <- filter(bird.vars, location == "shabby")
  shab.herg <- filter(herg.vars, location == "shabby")
  shab.gbbg <- filter(gbbg.vars, location == "shabby")
  shab.coei <- filter(coei.vars, location == "shabby")
hrn.vars <- filter(bird.vars, location == "heron")
  hrn.herg <- filter(herg.vars, location == "heron")
  hrn.gbbg <- filter(gbbg.vars, location == "heron")
  hrn.coei <- filter(coei.vars, location == "heron")
sch.vars <- filter(bird.vars, location == "schoodic")
  sch.herg <- filter(herg.vars, location == "schoodic")
  sch.gbbg <- filter(gbbg.vars, location == "schoodic")
  sch.coei <- filter(coei.vars, location == "schoodic")
gdi.vars <- filter(bird.vars, location == "gdi")
  gdi.herg <- filter(herg.vars, location == "gdi")
  gdi.gbbg <- filter(gbbg.vars, location == "gdi")
  gdi.coei <- filter(coei.vars, location == "gdi")
  
```

```{r}
bird.vars.2 <- bird.vars %>% filter(!(is.na(cover)))
bird.vars.2 <- bird.vars.2[is.na(bird.vars.2)] <- "0"
```

```{r veg.vars}
n_herg <- herg_buff %>%
  select(!"species") %>%
  rename("herg_count" = "Join_Count")

n_gbbg <- gbbg_buff %>%
  select(!"species") %>%
  rename("gbbg_count" = "Join_Count")

n_coei <- coei_buff %>%
  select(!"species") %>%
  rename("coei_count" = "Join_Count")

veg.vars.herg <- left_join(island_veg_all, herg_buff, by = "gps") 
veg.vars.gbbg <- left_join(island_veg_all, gbbg_buff, by = "gps")
veg.vars.coei <- left_join(island_veg_all, coei_buff, by = "gps")

# veg.vars <- left_join(island_veg_all, ) %>%
#   left_
```

